assets:
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  secring.gpg: yegor256/home#assets/secring.gpg
  pubring.gpg: yegor256/home#assets/pubring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |-
    mvn clean install -Pqulice-profile -Pqulice --errors --batch-mode
    ./years.sh
deploy:
  script: |-
    mvn clean deploy -Pqulice-profile -Pqulice --errors --settings ../settings.xml
release:
  pre: false
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice-profile -Psonatype --errors --settings ../settings.xml
    # mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml
    # mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml
