---
name: reports-check
'on':
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: tracehubpm/reports-check-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #deepinfra_token: ${{ secrets.DEEPINFRA_TOKEN }}
          openai_token: ${{ secrets.OPENAI_TOKEN }}
